services:

  postgres-dev:
    image: postgres
    restart: always
    networks:
      - transcribedb_default
    volumes:
      - postgres:/media/apps4/postgres/db:rw
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: devuser321
      POSTGRES_USER: devuser
      POSTGRES_DB: transcribeapp_db
      PGDATA: /media/apps4/postgres/db
networks:
  dbnet:
    driver: bridge

volumes:
  postgres:
