# Use postgres/example user/password credentials
version: '3.1'

services:

  transcribeapp-dev:
    image: postgres
    container_name: transcribeapp-dev
    restart: always
    volumes:
        - /opt/apps/scripts/alias.sh:/home/alias.sh
        - ./my-postgres.conf:/etc/postgresql/postgresql.conf
        - ./scripts/sql/transcribedb.ddl:/docker-entrypoint-initdb.d/1-transcribedb.ddl
        - ./scripts/sql/postgres_master_data_import.data:/docker-entrypoint-initdb.d/2-postgres_master_data_import.data
        - ./scripts/sql/us_cities.sql:/docker-entrypoint-initdb.d/3-us_cities.sql
        - postgresdb-data:/media/apps4/postgres/db:rw
        - /media/apps4/postgres/db:/media/apps4/postgres/db:rw
    env_file:
        - ./scripts/env_file
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
        - 6432:5432
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: transcribeapp_db
      PGDATA: /opt/apps/postgres/db
    networks:
        - dbnet
        
volumes:
  postgresdb-data:
networks:
  dbnet:
    driver: bridge

