
# Use postgres/example user/password credentials
version: '3'

services:
  transcribeapp-dev:
    env_file: ./scripts/env-$NODE_ENV.conf
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:12-alpine
    container_name: "${POSTGRES_DB}_${NODE_ENV}-db"
    restart: always
    volumes:
        - ./app-bin/:/opt/apps/app-bin/:rw
        - ./my-postgres.conf:/etc/postgresql/postgresql.conf
        - ./scripts/sql/:/docker-entrypoint-initdb.d/
        - pg-data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
        - 6432:5432
    networks:
        - dbnet
networks:
  dbnet:
    driver: bridge
