# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres-dev:
    image: postgres
    restart: always
    volumes:
      - postgres:/media/apps4/postgres/db:rw
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: devuser321
      POSTGRES_USER: devuser
      POSTGRES_DB: transcribeapp_db
      PGDATA: /media/apps4/postgres/db

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin4:/media/apps4/postgres/pgAdmin4/.pgadmin
      - ./scripts:/media/apps4/postgres/pgAdmin4/storage/user/
    ports:
      - '5050:80'
    networks:
      - dbnet
    environment:
      PGADMIN_DEFAULT_EMAIL: devappuser@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: devuser321

  adminer:
    image: adminer
    restart: always
    networks:
      - postgres-bridge
    ports:
      - 5051:8080
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  postgres:
  pgadmin4:
  adminer:
